### ISSUE TITLE
routes.php exists

### ISSUE THREAD

**Issue by dimti** [SaifurRahmanMohsin/RESTful-Plugin#6]
Hi

I try to using our plugin and fetched discourage me error

``` [Exception]                                                                                            
  Stop everything!!! This file already exists: /var/www/myproject/plugins/dimti/myplugin/routes.php  
```

I use this file for custom code. How to resolve that conflict in create rest controller?

**Comment by SaifurRahmanMohsin** [comment]
You can use custom routes.php file, the plugin would still work fine. I’ll tell you how to overcome this:

#### Method 1 #####
Make a backup of your routes.php file, delete the http folder entirely and run the restcontroller scaffolding command again. Open routes.php, copy the code inside it (except the first line — namespace declaration) and then delete the file, put back your original routes.php which you backed up and paste the code which you copied at the end of the file.

#### Method 2 #####
Just add the code manually in the following format:

```
Route::group(['prefix' => 'api/v1'], function () {
    Route::resource('{{lower_plural_controller_name}}', ‘{{plugin_author_name}}\{{plugin_name}}\Http\{{controller_name}}');
});
```

So if you want to expose the **Person** controller in **Acme.People** plugin then it should look like:
```
Route::group(['prefix' => 'api/v1'], function () {
    Route::resource(‘persons', ‘Acme\People\Http\Person');
});
```

Let me know if this solves the issue. And if you like the plugin kindly drop a good review, good day.

**Comment by dimti** [comment]
Please, give me info (links, books, publications) about restfull api. Im beginner with creates of api.. and have more fantasy about that aspect. I can add custom api-methods(actions) to one controller? why, if not?
add validation / define input data, define http-method for every action.. But laravel Route::resource slice my fantasy about api.

**Comment by SaifurRahmanMohsin** [comment]
There are several features that this plugin has missing and I will add eventually—these include better API versioning, auth packages support to secure API using auth scheme of user's choice, and many more interesting features. This would all take a while to create so I’m glad you want to learn to write custom code. Here are some links that I think may help you with this:

https://laravel.com/docs/5.0/controllers#restful-resource-controllers
http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

I do not know of any popular books or publications on the matter but I do have plans to make video tutorials in future as I have experience building large apps using RESTful APIs. If I do publish these videos in the future I’ll let you know then, otherwise you may have to learn on your own. Happy learning, good day.

**Comment by SaifurRahmanMohsin** [comment]
There are several features that this plugin has missing and I will add eventually—these include better API versioning, auth packages support to secure API using auth scheme of user's choice, and many more interesting features. This would all take a while to create so I’m glad you want to learn to write custom code. Here are some links that I think may help you with this:

https://laravel.com/docs/5.0/controllers#restful-resource-controllers
http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

> I can add custom api-methods(actions) to one controller?

Yes, please check out [the plugin’s documentation](http://octobercms.com/plugin/mohsin-rest#documentation) on how to do this. You basically have to specify the method in the config and then write the function for it inside the Http folder in the write RESTful controller file.

> add validation / define input data

Yes, you can add custom validation code by overloading the default actions, or if it’s a custom action then just add the validation to that. Read [OctoberCMS documentation](http://octobercms.com/docs/services/validation) on how to do validation. You create the validator class instance inside the action and do it. If you stick to the default then RESTful plugin uses the same model’s validation for validating data.

I do not know of any popular books or publications on the matter but I do have plans to make video tutorials in future as I have experience building large apps using RESTful APIs. If I do publish these videos in the future I’ll let you know then, otherwise you may have to learn on your own. Happy learning, good day.
